APPS-2914  & APPS-2915 Search UI Updates
openlattice/lattice-orgs pull request #1042
Opened 2021-05-05 22:04 UTC by bergieboy

![Screen Shot 2021-05-05 at 3 03 41 PM](https://user-images.githubusercontent.com/19995069/117215472-1c457f80-adb3-11eb-8c4c-075f74f5d107.png)

2021-05-05 22:18 UTC, solomontang approved these changes

2021-05-05 22:53 UTC, UnsungHero97 requested changes

2021-05-05 22:53 UTC, UnsungHero97 commented on src/core/router/Routes.js
> +const ORG_DATA_SET_DATA :'/orgs/:organizationId/dataSets/:dataSetId/search' = `${ORG_DATA_SET}/search`;
I don't think this change is necessary. We can't actually search external data sets (yet) so this will be only half true.

2021-05-05 22:53 UTC, UnsungHero97 commented on src/components/other/NavContentWrapper.js
> +
This is not necessary. You can just pass the `borderless` prop.

2021-05-05 22:53 UTC, UnsungHero97 commented on src/containers/org/OrgDataSetContainer.js
> +`;
Please use `Typography` component, example in my next comment.

2021-05-05 22:53 UTC, UnsungHero97 commented on src/containers/org/OrgDataSetContainer.js
> +            <NavLink exact strict to={dataSetRoute}>Properties</NavLink>
```suggestion
          <AppNavigationWrapper borderless>
            <NavLink exact strict to={dataSetRoute}>
              <Typography variant="h3">Properties</Typography>
            </NavLink>
```

2021-05-05 23:49 UTC, UnsungHero97 approved these changes

2021-05-05 23:55 UTC, UnsungHero97 commented
test comment

2021-05-06 01:49 UTC, UnsungHero97 commented
test comment

2021-05-07 19:15 UTC, solomontang approved these changes

2021-05-07 19:16 UTC, merged