Feature/apps 3025 initial collaboration view
openlattice/lattice-orgs pull request #1150
Opened 2021-07-09 01:57 UTC by bergieboy

*WILL UPDATE BASE BRANCH WHEN APPS-2995 IS MERGED*

This adds the initial Collaborations View

<img width="1686" alt="Screen Shot 2021-07-08 at 6 53 16 PM" src="https://user-images.githubusercontent.com/19995069/125011953-35bab000-e01e-11eb-96e1-95be27550d99.png">

2021-07-09 15:06 UTC, anzioka commented on src/containers/collaborations/components/CreateCollaborationModal.js
> +            <Select
I believe the `htmlFor` value should be equal to the `id` attribute of the corresponding input element

2021-07-09 15:06 UTC, anzioka commented on src/containers/collaborations/components/CreateCollaborationModal.js
> +      dispatch(
just checking, shouldn't the `collaborationName` be an nonEmptyString as well?

2021-07-09 15:47 UTC, UnsungHero97 commented on src/containers/collaborations/CollaborationsContainer.js
> +  ));
I actually think matching against the id is super convenient, even if it's only taken advantage of internally. Sometimes I have an id and I just want to find the thing with that id. We already have this for matching org ids.

Using something like `.startsWith()` or `.includes()` over `===` might be better user experience.

2021-07-09 15:49 UTC, UnsungHero97 commented on src/containers/collaborations/components/CreateCollaborationModal.js
> +  };
Only thing I'd change is `useReducer` over `useState(fancyObject)`.

2021-07-09 18:23 UTC, anzioka commented on src/containers/collaborations/CollaborationsContainer.js
> +    }
Also, I think it makes sense to call `dispatch(getCollaborations())` once and update the redux store after creating new collaborations.

2021-07-09 18:37 UTC, bergieboy commented on src/containers/collaborations/CollaborationsContainer.js
> +  ));
I'm going to keep the id filter and use `.includes()`

2021-07-09 23:47 UTC, anzioka commented on src/containers/collaborations/components/CreateCollaborationModal.js
> +  const [isValidCollaborationName, setIsValidCollaborationName] = useState(true);
the reducer state has `nameIsValid` and `titleIsValid`.

2021-07-09 23:47 UTC, anzioka commented on src/containers/collaborations/CollaborationsContainer.js
> +    }
I still think  `dispatch(getCollaborations())` should only be called once, unless I'm missing something.
https://github.com/openlattice/lattice-orgs/pull/1150#discussion_r667135964

2021-07-12 22:11 UTC, anzioka submitted a review, later dismissed

2021-07-13 17:36 UTC, giuliacampana submitted a review, later dismissed

2021-07-19 17:36 UTC, UnsungHero97 requested changes

2021-07-19 17:36 UTC, UnsungHero97 commented on src/containers/collaborations/reducers/renameCollaborationDatabaseReducer.js
> +          .setIn([COLLABORATIONS, collaborationId, TITLE], name)
Renaming the database is independent of the title of the collaboration. You need to update the value in `DATABASE_DETAILS`.

2021-07-20 02:41 UTC, UnsungHero97 approved these changes

2021-07-20 16:27 UTC, anzioka approved these changes

2021-07-20 16:39 UTC, giuliacampana approved these changes

2021-07-20 17:25 UTC, solomontang approved these changes

2021-07-20 19:29 UTC, merged