Feature/apps 3041 data set collaborations
openlattice/lattice-orgs pull request #1167
Opened 2021-07-21 00:56 UTC by solomontang

![image](https://user-images.githubusercontent.com/27182199/126413681-f6621615-8070-47a7-8f51-8f5fa31ff534.png)

2021-07-21 01:42 UTC, anzioka submitted a review, later dismissed

2021-07-21 16:47 UTC, giuliacampana approved these changes

2021-07-21 20:35 UTC, anzioka approved these changes

2021-07-21 20:35 UTC, bergieboy approved these changes

2021-07-21 20:39 UTC, giuliacampana approved these changes

2021-07-22 01:22 UTC, UnsungHero97 requested changes

2021-07-22 01:22 UTC, UnsungHero97 commented on src/containers/org/OrgContainer.js
> +  const collaborationHref = ORG_COLLABORATIONS.replace(':organizationId', organizationId);
Please use `ORG_ID_PARAM` in the routes file.

```suggestion
  const collaborationHref = ORG_COLLABORATIONS.replace(ORG_ID_PARAM, organizationId);
```

2021-07-22 01:22 UTC, UnsungHero97 commented on src/containers/org/OrgContainer.js
> +  const orgHref = ORG.replace(':organizationId', organizationId);
Please use `ORG_ID_PARAM` in the routes file.

```suggestion
  const orgHref = ORG.replace(ORG_ID_PARAM, organizationId);
```

2021-07-22 01:22 UTC, UnsungHero97 commented on src/containers/org/OrgContainer.js
> +            <FolderTab
It's safe to delete `TabPanel` now, right?

2021-07-22 01:22 UTC, UnsungHero97 commented on src/core/router/Routes.js
> +const ORG_COLLABORATIONS :'/orgs/:organizationId/collaborations' = `${ORGS}/${ORG_ID_PARAM}/collaborations`;
No change required, just flagging it for visibility. We're now using both `/collabs` (defined above) and `/collaborations` (defined here). I would prefer if these matched.

2021-07-22 03:20 UTC, anzioka approved these changes

2021-07-22 16:05 UTC, UnsungHero97 approved these changes

2021-07-22 16:06 UTC, merged