Add Entity Type to Data Set Container
openlattice/lattice-orgs pull request #1280
Opened 2021-09-27 18:53 UTC by bergieboy

2021-09-27 19:17 UTC, solomontang approved these changes

2021-09-27 22:37 UTC, anzioka approved these changes

2021-09-28 16:44 UTC, UnsungHero97 requested changes

2021-09-28 16:44 UTC, UnsungHero97 commented on src/containers/org/OrgDataSetContainer.js
> +    : null;
`type` is an FQN so you don't need to manually construct the string ... just call `.toString()`. However, I would simplify this by removing this assignment and making the change below.

```suggestion
```

2021-09-28 16:44 UTC, UnsungHero97 commented on src/containers/org/OrgDataSetContainer.js
> +                }
```suggestion
                {
                  entityType && (
                    <>
                      <Typography variant="subtitle1">DATA SET TYPE</Typography>
                      <Typography gutterBottom>{entityType.type.toString()}</Typography>
                    </>
                  )
                }
```

2021-09-28 17:09 UTC, UnsungHero97 requested changes

2021-09-28 17:09 UTC, UnsungHero97 commented on src/containers/org/OrgDataSetContainer.js
> +                      <Typography gutterBottom>{entityType.toString()}</Typography>
```suggestion
                      <Typography gutterBottom>{entityType.type.toString()}</Typography>
```

2021-09-28 17:14 UTC, UnsungHero97 approved these changes

2021-09-28 17:14 UTC, solomontang approved these changes

2021-09-28 17:15 UTC, merged