permissions toggle for selecting only non-pii properties
openlattice/lattice-orgs pull request #666
Opened 2020-10-16 17:02 UTC by UnsungHero97

Depends on https://github.com/openlattice/lattice-orgs/pull/665

2020-10-16 18:31 UTC, giuliacampana submitted a review, later dismissed

2020-10-16 23:16 UTC, bergieboy requested changes

2020-10-16 23:16 UTC, bergieboy commented on src/containers/org/components/PermissionsPanel.js
> +          </IconButton>
please add the aria-label attribute to buttons that don't contain text. The label should clearly describe the destination, purpose, function, or action for screen reader users.

2020-10-16 23:16 UTC, bergieboy commented on src/containers/org/components/PermissionsPanel.js
> +          </IconButton>
please add the aria-label attribute to buttons that don't contain text. The label should clearly describe the destination, purpose, function, or action for screen reader users.

2020-10-21 17:10 UTC, bergieboy requested changes

2020-10-21 17:10 UTC, bergieboy commented on src/containers/org/components/PermissionsPanel.js
> +          <IconButton onClick={togglePermissionAssignmentOnlyNonPII}>
this one also needs a label

2020-10-21 17:15 UTC, bergieboy approved these changes

2020-10-21 20:44 UTC, solomontang approved these changes

2020-10-21 21:10 UTC, merged