Feature/apps 2576 entity set assembly
openlattice/lattice-orgs pull request #773
Opened 2020-12-09 06:08 UTC by solomontang

- Surface Assemble/Disassemble action in the data set action menu
  - user must have the `MATERIALIZE` permission on the entity set
  - enabled only for openlattice entity sets

2020-12-09 12:16 UTC, anzioka approved these changes

2020-12-10 02:28 UTC, bergieboy submitted a review, later dismissed

2020-12-10 02:28 UTC, bergieboy commented on src/containers/org/components/dataset/AssembleMenuItem.js
> +  const isLoading = isPending(destroyRS) || isPending(transportRS);
```isPending(reduceRequestStates([destroyRS, transportRS]);```

2020-12-10 12:29 UTC, anzioka approved these changes

2020-12-10 17:48 UTC, bergieboy submitted a review, later dismissed

2020-12-15 06:59 UTC, UnsungHero97 approved these changes

2020-12-15 06:59 UTC, UnsungHero97 commented on src/containers/org/DataSetMetaContainer.js
> +      acl: [dataSetId],
This should technically be `aclKey`, but since the name implies a single data set, you could also change it to just `dataSetId`.

2020-12-15 06:59 UTC, UnsungHero97 commented on src/containers/org/components/dataset/AssembleMenuItem.js
> +  disabled :boolean;
Why not `isDisabled`?

2020-12-15 06:59 UTC, UnsungHero97 commented on src/containers/org/components/dataset/DataSetActionButton.js
> +            organizationId={organizationId} />
I thought we decided it should not be visible if it's an atlas data set, i.e. only show for entity sets?

2020-12-15 06:59 UTC, UnsungHero97 commented on src/core/edm/reducers/transportOrganizationEntitySetReducer.js
> +          const flags = [...entitySet.flags, EntitySetFlagTypes.TRANSPORTED];
It's a good idea to wrap this with a `Set` to avoid duplicates.

2020-12-15 06:59 UTC, UnsungHero97 commented on src/core/permissions/sagas/getCurrentDataSetAuthorizations.js
> +        .setAclKey(acl)
`acl` has a different meaning.

2020-12-15 07:00 UTC, UnsungHero97 requested changes
Accidentally submitted with "Approve" instead of "Request changes".

2020-12-15 07:28 UTC, solomontang commented on src/containers/org/components/dataset/AssembleMenuItem.js
> +  disabled :boolean;
material api

2020-12-21 19:29 UTC, anzioka approved these changes

2020-12-22 00:32 UTC, UnsungHero97 approved these changes

2020-12-22 00:32 UTC, merged