Task/APPS-2851 — go to new org page on createNewOrg
openlattice/lattice-orgs pull request #984
Opened 2021-04-05 16:36 UTC by giuliacampana

![b51d5e7001c31f26645c7b69a87d3086](https://user-images.githubusercontent.com/32921059/113598707-64298900-95f2-11eb-985d-a799cc7681f3.gif)

2021-04-05 18:15 UTC, UnsungHero97 requested changes

2021-04-05 18:15 UTC, UnsungHero97 commented on src/containers/org/reducers/index.js
> +  [NEW_ORGANIZATION]: Map(),
This should not be a `Map` because it does not match the `Organization` type.

2021-04-06 01:08 UTC, giuliacampana commented on src/containers/org/components/CreateOrgModal.js
> +    { organization },
you're right—it's not necessary. removed this.

2021-04-06 01:14 UTC, giuliacampana commented on src/containers/org/components/CreateOrgModal.js
> +  const organization :Organization | Map = useSelector((store) => store.getIn([ORGANIZATIONS, NEW_ORGANIZATION]));
will create a selector. changed the reducer to store just the org id so the type is UUID now.

2021-04-06 01:29 UTC, UnsungHero97 approved these changes

2021-04-06 21:22 UTC, solomontang approved these changes

2021-04-06 21:48 UTC, merged